### ISSUE TITLE
Blank Screen for Live Demo (iOS)

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [jnmaloney/WebGui#4]
The demo didn’t work for me when clicking through on my iPhone 12. See the video.

thanks for putting this project to together, I used to make games and now code exclusively in JS. IMGUI is one of the good ones I miss.

https://user-images.githubusercontent.com/34040155/106400764-85051080-63ee-11eb-96d6-41db195ded1b.MP4

**Comment by Jerem584** [comment]
same problem on macos / problem is due to safari

**Comment by Francois-Laberge-Bose** [comment]
Ah that's good at least, then it's easier to debug. Here's the error on macOS Safari:

**Screenshot**
<img width="300" alt="Screen Shot 2021-02-01 at 9 44 39 AM" src="https://user-images.githubusercontent.com/34040155/106473784-35682880-6472-11eb-8b9f-2fcbeeaba0d3.png">


**Text of Console Output**
```
[Error] Failed to load resource: the server responded with a status of 404 () (favicon.ico, line 0)
[Log] Shader complete #3 (imgui.js, line 1)
[Log] Shader complete #4 (imgui.js, line 1)
[Error] WebGL: INVALID_ENUM: pixelStorei: invalid parameter name
	pixelStorei
	_glPixelStorei (imgui.js:1:117797)
	wasm-stub
	<?>.wasm-function[104]
	<?>.wasm-function[102]
	<?>.wasm-function[90]
	<?>.wasm-function[1480]
	wasm-stub
	dynCall_v
	(anonymous function) (imgui.js:1:158631)
	browserIterationFunc (imgui.js:1:96336)
	runIter (imgui.js:1:78657)
	Browser_mainLoop_runner (imgui.js:1:97576)
[Log] 0x9 (imgui.js, line 1)
[Log] 9 (imgui.js, line 1)
[Error] WebGL: INVALID_ENUM: getParameter: invalid parameter name
	getParameter
	emscriptenWebGLGet (imgui.js:1:115014)
	_glGetIntegerv (imgui.js:1:116317)
	wasm-stub
	<?>.wasm-function[105]
	<?>.wasm-function[90]
	<?>.wasm-function[1480]
	wasm-stub
	dynCall_v
	(anonymous function) (imgui.js:1:158631)
	browserIterationFunc (imgui.js:1:96336)
	runIter (imgui.js:1:78657)
	Browser_mainLoop_runner (imgui.js:1:97576)
[Error] TypeError: GLctx["bindSampler"] is not a function. (In 'GLctx["bindSampler"](unit,GL.samplers[sampler])', 'GLctx["bindSampler"]' is undefined)
	runIter (imgui.js:1:78789)
	Browser_mainLoop_runner (imgui.js:1:97576)
```

**Comment by jnmaloney** [comment]
Ah thanks for letting me know. I'll keep looking into seeing if there's anything I can do.

Also I'm glad you enjoy the project but I should let you know that it's getting a bit old and I think that the features that I added to get it working are now integrated into ImGui itself.

**Comment by Francois-Laberge-Bose** [comment]
No worries. I looked around some more and found another project that had a pretty flushed out implementation. It had a safari issue too though, but it was fixed today. See
https://github.com/flyover/imgui-js/issues/37.

No worries if you want to close this, was just leaving an issue to give you feedback

**Comment by Jerem584** [comment]
Sorry to up this, but for a project I did retake a look at this project and seems like the demo website is working fine on iPhone 13 pro max iOS 15.1.1
Using safari

**Comment by luxe** [comment]
based on the color of the background, I think it loaded correctly, its just that a phone's viewport is too small to see any of the GUI elements
